### ISSUE TITLE
How to initialize and run

### ISSUE THREAD

**Issue by hieuvtd00195** [sven-n/MuMain#14]
Please give me instructions to run it

**Comment by sven-n** [comment]
* You need Visual Studio 2022 with the newest update, workloads for C++ and C#
* Requires .NET Runtime 8.0.0, x86: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-8.0.0-windows-x86-installer
* Because of the integrated .NET code, you need to publish the ManagedLibrary first to the debug output folder of the main.exe, so that all required managed DLLs are copied. A simple build is not enough in this case, however the publish just needs to be done once.

**Comment by hieuvtd00195** [comment]
Bro, is there a discord community? I want to join for easy communication
Vào Thứ Hai, 11 tháng 12, 2023, sven-n ***@***.***> đã viết:

**Comment by sven-n** [comment]
sure, we can communicate here: https://discord.com/channels/669595902750490698/1091671769875763311

**Comment by komandirbk** [comment]
> sure, we can communicate here: https://discord.com/channels/669595902750490698/1091671769875763311

link doesn't work bro
