### ISSUE TITLE
Random exception while hunting in Tarkan

### ISSUE THREAD

**Issue by nitoygo** [sven-n/MuMain#45]
While killing monsters in Tarkan for my dark stone quest, there are times when the client randomly crashes.
Not sure of the actual trigger...

Pasting here the call trace when the incident happens:
![image](https://github.com/user-attachments/assets/3dad6375-dc06-4d33-b45a-b30cfdb4e7fb)

**Comment by sven-n** [comment]
The value of `o->Type` seems to be too high... `9521 - 1171 = 8350`
Maximum type value should be: `512 * 16 = 8192`, see also constant `MAX_ITEM`. Now the big question is: how did it get this value? 😅

**Comment by sven-n** [comment]
Idea: could've been caused by the same bug as the ancient bug. The server wrote some options at a higher index as it should, possibly into the item group/number of the next item. So when dropping multiple items, this could've happened...
Can you reproduce the issue with the current OpenMU main branch?

**Comment by nitoygo** [comment]
From the call stack, it shows "Kris". could this be caused by Excellent Kris? haha. but this happened to me more than twice already. and picking up an excellent item that frequent seems weird

**Comment by nitoygo** [comment]
I don't encounter this anymore. Closing...
